- name: Deploy Static HTML App
  hosts: web
  become: yes

  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy app files
      copy:
        src: ../app/index.html
        dest: /var/www/html/
        mode: '0755'

    - name: Update NGINX config
      copy:
        src: ../nginx/nginx.conf
        dest: /etc/nginx/sites-available/default
        mode: '0644'

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

